import time
print("game start")
time.sleep(.5)
name = input("Choose your name: ")
print("\n\nIt is 1789")
print("\nYou are "+name)
time.sleep(1)
print("\nYou are a professional assasin in America")
time.sleep(3)
print("\nYou have deep hatred for the Americans after they colonised the New World")
time.sleep(3)
print("\nYou are ordered to assasinate a high profile figure.")
time.sleep(3)
print("\nYour boss tells you..")
time.sleep(2)
print("\n"+"'"+name+", I want you to assasinate the man who will become president, to give me a chance to become president myself!'")
time.sleep(2)
print("\nYou leave the house and make your way down to the adress that was written on a note your boss gave you..")
time.sleep(2)
print("\n.. '1600 Pennsylvania Avenue NW in Washington, D.C'")

